// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOMchqmwOb5fa3er0o2x-UYFR3aVN8epI',
    appId: '1:527736804612:web:cabb5f6721b5b88a08ac51',
    messagingSenderId: '527736804612',
    projectId: 'line-a-day-d8fe5',
    authDomain: 'line-a-day-d8fe5.firebaseapp.com',
    storageBucket: 'line-a-day-d8fe5.firebasestorage.app',
    measurementId: 'G-2KRMMEFPM3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjN5lnH1NE15CLigW3ZOaAXRqicq4e8bY',
    appId: '1:527736804612:android:cfcabcc8f0f12bd108ac51',
    messagingSenderId: '527736804612',
    projectId: 'line-a-day-d8fe5',
    storageBucket: 'line-a-day-d8fe5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRT2CVRwH3gkf22LYAhU8k6w92lETZX-c',
    appId: '1:527736804612:ios:1e5d97dab7e0f99008ac51',
    messagingSenderId: '527736804612',
    projectId: 'line-a-day-d8fe5',
    storageBucket: 'line-a-day-d8fe5.firebasestorage.app',
    iosBundleId: 'com.example.lineADay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRT2CVRwH3gkf22LYAhU8k6w92lETZX-c',
    appId: '1:527736804612:ios:1e5d97dab7e0f99008ac51',
    messagingSenderId: '527736804612',
    projectId: 'line-a-day-d8fe5',
    storageBucket: 'line-a-day-d8fe5.firebasestorage.app',
    iosBundleId: 'com.example.lineADay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOMchqmwOb5fa3er0o2x-UYFR3aVN8epI',
    appId: '1:527736804612:web:ed9d434267e1a19e08ac51',
    messagingSenderId: '527736804612',
    projectId: 'line-a-day-d8fe5',
    authDomain: 'line-a-day-d8fe5.firebaseapp.com',
    storageBucket: 'line-a-day-d8fe5.firebasestorage.app',
    measurementId: 'G-VXRECDQJ0T',
  );
}
